#+TITLE: Doom Emacs Configuration
#+AUTHOR: Seshal Jain
#+PROPERTY: header-args:emacs-lisp :tangle yes :results silent

#+BEGIN_QUOTE
I’m sure I’ll be tweaking it forever though, it’s almost as satisfying
as actually using it.
#+END_QUOTE

Make this file run (slightly) faster with lexical binding
#+BEGIN_SRC emacs-lisp
;;; config.el -*- lexical-binding: t; -*-
#+END_SRC

* Personal Information
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Seshal Jain"
      user-mail-address "seshaljain11@gmail.com")
#+END_SRC

Set up =authinfo.gpg=
#+begin_src emacs-lisp :tangle yes
(setq auth-sources '("~/.authinfo.gpg")
      auth-source-cache-expiry nil) ; default is 7200 (2h)
#+end_src

* Better Defaults
** UI
Font
#+BEGIN_SRC emacs-lisp
(setq! doom-font (font-spec :family "Iosevka Term Curly" :size 24 :weight 'semi-bold))
#+END_SRC

Theme
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-solarized-light)
#+END_SRC

Fullscreen
#+BEGIN_SRC emacs-lisp
(set-frame-parameter (selected-frame) 'fullscreen 'maximized)
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+END_SRC

Prefer vertical splits
#+BEGIN_SRC emacs-lisp
(setq split-width-threshold 120)
#+END_SRC

No icons in mode line
#+BEGIN_SRC emacs-lisp :tangle yes
(setq! doom-modeline-icon nil)
#+END_SRC

* Packages
:PROPERTIES:
:header-args:emacs-lisp: :tangle packages.el :results silent
:END:
Define =package!= and =use-package!= declaration in the same section

All package install directives are tangled to =packages.el= while all package configurations are tangled to =config.el=.
The trick is to set =:tangle packages.el= to this section, and specify =:tangle yes= to all config blocks. This tangles them to =config.el=, the default tangle file for this document. Ingenious ;)

This file shouldn't be byte compiled
#+begin_src emacs-lisp
;; -*- no-byte-compile: t; -*-
#+end_src

** org
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package! org
  :init
  (setq! org-directory "~/Documents/Org")
  :config
  (setq! org-edit-src-content-indentation 0
         org-src-window-setup 'current-window
         org-log-done 'time
         org-log-done-with-time nil))
#+END_SRC

*** Org Agenda
#+begin_src emacs-lisp :tangle yes
(use-package! org
  :config
  (setq! org-agenda-files (list org-directory (concat org-directory "/roam")))))
#+end_src

*** Org Capture
Capture templates for quick notetaking
#+BEGIN_SRC emacs-lisp :tangle yes
(after! org
  (defun my/add-journal-metadata ()
    "Get the date for org-capture in the format YYYY-MM-DD."
    (let ((datestamp (org-capture-get :date)))
      (org-entry-put nil "EXPORT_FILE_NAME" (format-time-string "%Y-%m-%d" datestamp))
      (org-entry-put nil "EXPORT_DATE" (format-time-string "%Y-%m-%d" datestamp)))))

  (use-package! org
    :config

;; Org-roam base
(setq! org-roam-directory (file-truename "~/org/"))
(org-roam-db-autosync-mode 1)

;; Optional: agenda + logging (keeps state/clock logs in a drawer)
(setq! org-agenda-files '("~/org/dsa"))
(setq! org-log-into-drawer t)
(setq! org-todo-keywords
      '((sequence "TODO(t)" "IN-PROGRESS(i!)" "REVIEW(r!)" "|" "DONE(d!)" "SKIP(k)")))

;; Org-roam capture templates (no timestamps in filenames; slug-only)
(setq! org-roam-capture-templates
      '(
        ;; Question (no Problem or Tests; C++ only)
        ("q" "Question" plain
         "%?"
         :if-new (file+head "questions/${slug}.org"
                            "#+title: ${title}\n\
,#+filetags: :%^G:%^{difficulty|easy|medium|hard}:cpp:\n\
,#+roam_alias: %^{Aliases (optional)|}\n\
,#+roam_refs: %^{Reference URL (optional)}\n\
\n* TODO Practice ${title}\n:LOGBOOK:\n:END:\n\
\n* Approach\n- [ ] Brute force\n- [ ] Optimal\n\
\n* Code\n#+begin_src cpp\n%?\n#+end_src\n\
\n* Insights\n- Patterns:\n- Pitfalls:\n\
\n* Links\n;; Insert Topic/Sheet links with M-x org-roam-node-insert\n")
         :unnarrowed t)

        ;; Topic node (tag with :topic:<slug>:)
        ("t" "Topic" plain
         "%?"
         :if-new (file+head "topics/${slug}.org"
                            "#+title: ${title}\n#+filetags: :topic:${slug}:\n\
\n* Overview\n- Patterns:\n- Invariants:\n\n* Resources\n")
         :unnarrowed t)

        ;; Sheet node (tag with :sheet:<slug>:)
        ("s" "Sheet" plain
         "%?"
         :if-new (file+head "sheets/${slug}.org"
                            "#+title: ${title}\n#+filetags: :sheet:${slug}:\n\
,#+roam_refs: %^{Source URL (optional)}\n\
\n* Description\n- Notes:\n\n* Plan\n- Target finish:\n")
         :unnarrowed t)
      ))))
    ;; (setq! org-capture-templates
          ;; '(("d" "DRI" entry
          ;;    (file+olp+datetree "~/Documents/Org/roam/dri.org")
          ;;    "* %?"
          ;;    :unnarrowed t)
          ;;   ("j" "Journal" plain
          ;;    (file+olp+datetree "~/Documents/journal/org/journal.org")
          ;;    "%?"
          ;;    :unnarrowed t
          ;;    :jump-to-captured t
          ;;    :before-finalize my/add-journal-metadata))))
#+END_SRC
**** Org Roam Capture
#+begin_src emacs-lisp :tangle yes
(use-package! org-roam
  :after org
  :config (setq! org-roam-capture-templates
                 '(("l" "Log" item "- %u %?"
                    :target (file+olp "log.org" ("Log"))
                    :unnarrowed t
                    :prepend t)
                   ("w" "Work Item" plain "\n* Log\n\n* Summary\n%?\n\n* Resources"
                    :if-new (file+head "workitem/${slug}/%<%Y_%m_%d>_${slug}.org" "#+title: ${title}\n#+export_file_name: ${slug}\n#+options: num:nil toc:nil")
                    :unnarrowed t)
                   ("d" "default" plain "%?"
                    :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
                    :unnarrowed t))))
#+end_src

*** Org Export
Syntax highlighting via =Minted=
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package! org
  :config
  (setq! org-latex-listings 'minted
         org-latex-packages-alist '(("" "minted")
                                    ("" "xcolor"))
         org-latex-pdf-process
         '("xelatex -shell-escape -interaction nonstopmode -output-directory %o %f"
           "xelatex -shell-escape -interaction nonstopmode -output-directory %o %f"
           "xelatex -shell-escape -interaction nonstopmode -output-directory %o %f")))
        #+END_SRC

LaTeX class for college assignments
#+begin_src emacs-lisp :tangle yes
(use-package! ox-latex
  :config
  (add-to-list 'org-latex-classes
               '("assignment"
                 "\\documentclass[a4paper,12pt]{report}
\\usepackage{titlesec, color}
\\definecolor{gray75}{gray}{0.75}
\\newcommand{\\hsp}{\\hspace{10pt}}
\\titleformat{\\chapter}[hang]{\\Huge\\bfseries}{\\thechapter\\hsp\\textcolor{gray75}{|}\\hsp}{0pt}{\\Huge\\bfseries}
\\setlength{\\parindent}{0pt}
\\makeatletter
\\renewcommand{\\maketitle}{
  \\begin{titlepage}
    \\begin{center}
      \\vspace*{2em}
      \\Huge \\textbf{ASSIGNMENT} \\\\
      \\vspace{4em}
      \\Huge \\textbf{\\@title} \\\\
      \\vspace{4em}
      \\Large \\textbf{\\@date} \\\\
      \\bigskip
      \\Large \\textbf{\\@author} \\\\
      \\medskip
      \\large 191112436, CSE-3 \\\\
      \\bigskip
      \\includegraphics[width=16em]{../../manit-logo.png} \\\\
      \\bigskip
      \\large Department of Computer Science \\\\
      \\large MANIT, Bhopal \\\\
    \\end{center}
  \\end{titlepage}
}
\\makeatother
\\usepackage[margin=0.7in]{geometry}
\\usepackage{inconsolata}"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+end_src

Source code block formatting
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package! org
  :config
  (setq! org-latex-minted-options '(("breaklines" "true")
                                    ("breakanywhere" "true")
                                    ("style" "manni")
                                    ("frame" "lines"))))
#+END_SRC


** avy
Use Dvorak home row instead of Qwerty-default for avy navigation
#+BEGIN_SRC emacs-lisp :tangle yes
(use-package! avy
  :config
  (setq! avy-keys '(?a ?o ?e ?u ?h ?t ?n ?s)))
#+END_SRC

** company
Enable company completions in JS
#+begin_src emacs-lisp :tangle yes
(after! js2-mode
  (set-company-backend! 'js2-mode 'company-tide 'company-yasnippet))
#+end_src

** evil
Interim solution for Emacs launch error
https://github.com/doomemacs/doomemacs/issues/8203
#+begin_src emacs-lisp :tangle yes
(after! evil
  (define-key doom-leader-map (general--kbd "w") evil-window-map))
#+end_src
